<?php
/**
 * settings.ini.php
 * 
 * Defines initialization settings for mastodon.
 * DO NOT edit this file, to override these settings use settings.local.ini.php instead.
 * Any changes in the local ini file will override the settings found here.
 */

global $SETTINGS;

// tagged version
$SETTINGS['general']['application_name'] = 'mastodon';
$SETTINGS['general']['instance_name'] = $SETTINGS['general']['application_name'];
$SETTINGS['general']['version'] = '2.9';
$SETTINGS['general']['build'] = 'f67a192';

// which identifier to use when downloading participant data
$SETTINGS['general']['participant_data_identifier'] = NULL;

// the location of mastodon internal path
$SETTINGS['path']['APPLICATION'] = str_replace( '/settings.ini.php', '', __FILE__ );

// the location of new forms which need to be processed
$SETTINGS['path']['FORM_IN'] = $SETTINGS['path']['APPLICATION'].'/doc/form_in';

// the location of new forms which have been processed but not transferred to form system yet
$SETTINGS['path']['FORM_OUT'] = $SETTINGS['path']['APPLICATION'].'/doc/form_out';

// the location of supplementary data (for participant data access)
$SETTINGS['path']['SUPPLEMENTARY_DATA'] = NULL;

// add modules used by the application
$SETTINGS['module']['equipment'] = true;
$SETTINGS['module']['pdf'] = true;
$SETTINGS['module']['relation'] = true;
$SETTINGS['module']['script'] = true;
