<?php
/**
 * settings.ini.php
 * 
 * Defines initialization settings for mastodon.
 * DO NOT edit this file, to override these settings use settings.local.ini.php instead.
 * Any changes in the local ini file will override the settings found here.
 */

global $SETTINGS;

// tagged version
$SETTINGS['general']['application_name'] = 'mastodon';
$SETTINGS['general']['instance_name'] = $SETTINGS['general']['application_name'];
$SETTINGS['general']['version'] = '2.0.0';
$SETTINGS['general']['build'] = '2a5cd7b';

// always leave as false when running as production server
$SETTINGS['general']['development_mode'] = false;

// the location of mastodon internal path
$SETTINGS['path']['APPLICATION'] = '/usr/local/lib/mastodon';

// the location of new forms which need to be processed
$SETTINGS['path']['FORM_IN'] = $SETTINGS['path']['APPLICATION'].'/doc/form';

// the location to store processed consent forms
$SETTINGS['path']['FORM_OUT'] = $SETTINGS['path']['APPLICATION'].'/doc/data';
