#!/usr/bin/php
<?php
/**
 * This is a script that creates all dynamic database procedures
 * 
 * This script is necessary because mysql does not allow triggers to call procedures with dynamic SQL.
 * Some procedures depend on which applications are installed so our way around this limitation is to
 * create those procedures using this script.  The dynamic elements of the procedures are processed by
 * PHP instead of SQL.
 * 
 * @author Patrick Emond <emondpd@mcmaster.ca>
 */

ini_set( 'display_errors', '1' );
error_reporting( E_ALL | E_STRICT );
ini_set( 'date.timezone', 'US/Eastern' );

// utility functions
function out( $msg ) { printf( $msg."\n", $msg ); }
function error( $msg ) { out( sprintf( 'ERROR! %s', $msg ) ); die(); }


class patch
{
  /**
   * Reads the framework and application settings
   * 
   * @author Patrick Emond <emondpd@mcmaster.ca>
   * @access public
   */
  public function read_settings()
  {
    // include the initialization settings
    global $SETTINGS;
    $base_dir = getcwd();
    require_once $base_dir.'/settings.ini.php';
    require_once $base_dir.'/settings.local.ini.php';
    require_once $SETTINGS['path']['CENOZO'].'/src/initial.class.php';
    $initial = new \cenozo\initial( true );
    $this->settings = $initial->get_settings();
  }

  public function connect_database()
  {
    $server = $this->settings['db']['server'];
    $username = $this->settings['db']['username'];
    $password = $this->settings['db']['password'];
    $name = $this->settings['db']['database_prefix'] . $this->settings['general']['instance_name'];
    $this->db = new \mysqli( $server, $username, $password, $name );
    if( $this->db->connect_error ) error( $this->db->connect_error );
  }

  public function query( $sql )
  {
    $result = $this->db->query( $sql );
    if( false === $result ) error( $this->db->error );
    return $result;
  }

  /**
   * Executes the patch
   * 
   * @author Patrick Emond <emondpd@mcmaster.ca>
   * @access public
   */
  public function execute()
  {
    out( 'Reading configuration parameters' );
    $this->read_settings();

    out( 'Connecting to database' );
    $this->connect_database();

    $cenozo_db = sprintf( '%s%s', $this->settings['db']['database_prefix'], $this->settings['general']['framework_name'] );

    // loop through all applications which require participant sites to be updated
    $result = $this->query( <<<SQL
SELECT
  application.id AS application_id,
  application.name AS application_name,
  application_type.name AS application_type_name,
  site_based
FROM $cenozo_db.application
JOIN $cenozo_db.application_type ON application.application_type_id = application_type.id
ORDER BY application.name
SQL );

    $update_participant_site_for_participant_sql = <<<SQL
CREATE PROCEDURE $cenozo_db.update_participant_site_for_participant( IN proc_participant_id INT(10) UNSIGNED )
  BEGIN

SQL;

    while( $row = $result->fetch_assoc() )
    {
      $app_db = sprintf( '%s%s', $this->settings['db']['database_prefix'], $row['application_name'] );

      // always drop the triggers and procedure in case we're removing an application from the site_based category
      $this->query( sprintf( 'DROP TRIGGER IF EXISTS %s.jurisdiction_BEFORE_DELETE', $app_db ) );
      $this->query( sprintf( 'DROP TRIGGER IF EXISTS %s.region_site_BEFORE_DELETE', $app_db ) );
      $this->query( sprintf( 'DROP PROCEDURE IF EXISTS %s.update_participant_site_for_jurisdiction', $app_db ) );

      if( $row['site_based'] && 'alder' != $row['application_type_name'] )
      {
        $update_participant_site_for_participant_sql .= <<<SQL
    -- update {$row['application_name']}
    REPLACE INTO $cenozo_db.participant_site( application_id, participant_id, site_id, default_site_id )
    SELECT
      application_has_cohort.application_id,
      participant.id,
      IF(
        ISNULL( application_has_participant.preferred_site_id ),
        IF(
          application_has_cohort.grouping = "jurisdiction",
          jurisdiction.site_id,
          region_site.site_id
        ),
        application_has_participant.preferred_site_id
      ) AS site_id,
      IF(
        application_has_cohort.grouping = "jurisdiction",
        jurisdiction.site_id,
        region_site.site_id
      ) AS default_site_id
    FROM $cenozo_db.application_has_cohort
    JOIN $cenozo_db.participant ON application_has_cohort.cohort_id = participant.cohort_id
    LEFT JOIN $cenozo_db.participant_primary_address ON participant.id = participant_primary_address.participant_id
    LEFT JOIN $cenozo_db.address ON participant_primary_address.address_id = address.id
    LEFT JOIN $app_db.jurisdiction ON address.postcode = jurisdiction.postcode
    LEFT JOIN $cenozo_db.site AS jurisdiction_site ON jurisdiction.site_id = jurisdiction_site.id
    LEFT JOIN $cenozo_db.region ON address.region_id = region.id
    LEFT JOIN $app_db.region_site ON region.id = region_site.region_id
    LEFT JOIN $cenozo_db.site AS region_site_site
      ON region_site.site_id = region_site_site.id
      AND participant.language_id = region_site.language_id
    LEFT JOIN $cenozo_db.application_has_participant
      ON application_has_cohort.application_id = application_has_participant.application_id
      AND application_has_participant.participant_id = participant.id
    WHERE jurisdiction.site_id <=> jurisdiction_site.id
    AND region_site.site_id <=> region_site_site.id
    AND application_has_cohort.application_id = {$row['application_id']}
    AND participant.id = proc_participant_id;
SQL;

        out( sprintf( 'Creating %s.jurisdiction_BEFORE_DELETE trigger', $app_db ) );
        $this->query( <<<SQL
CREATE DEFINER=CURRENT_USER TRIGGER $app_db.jurisdiction_BEFORE_DELETE
  BEFORE DELETE ON $app_db.jurisdiction
  FOR EACH ROW

  BEGIN

    REPLACE INTO $cenozo_db.participant_site( application_id, participant_id, site_id, default_site_id )
    SELECT
      application_has_cohort.application_id,
      participant.id,
      application_has_participant.preferred_site_id,
      NULL
    FROM $cenozo_db.application_has_cohort
    JOIN $cenozo_db.participant ON application_has_cohort.cohort_id = participant.cohort_id
    LEFT JOIN $cenozo_db.participant_primary_address ON participant.id = participant_primary_address.participant_id
    LEFT JOIN $cenozo_db.address ON participant_primary_address.address_id = address.id
    LEFT JOIN $app_db.jurisdiction ON address.postcode = jurisdiction.postcode
    LEFT JOIN $cenozo_db.site AS jurisdiction_site ON jurisdiction.site_id = jurisdiction_site.id
    LEFT JOIN $cenozo_db.application_has_participant
      ON application_has_cohort.application_id = application_has_participant.application_id
      AND application_has_participant.participant_id = participant.id
    WHERE jurisdiction.site_id <=> jurisdiction_site.id
    AND application_has_cohort.application_id = {$row['application_id']}
    AND application_has_cohort.grouping = "jurisdiction"
    AND jurisdiction.id = OLD.id;

  END
SQL );

        out( sprintf( 'Creating %s.region_site_BEFORE_DELETE trigger', $app_db ) );
        $this->query( <<<SQL
CREATE DEFINER=CURRENT_USER TRIGGER $app_db.region_site_BEFORE_DELETE
  BEFORE DELETE ON $app_db.region_site
  FOR EACH ROW

  BEGIN

    REPLACE INTO $cenozo_db.participant_site( application_id, participant_id, site_id, default_site_id )
    SELECT
      application_has_cohort.application_id,
      participant.id,
      application_has_participant.preferred_site_id,
      NULL
    FROM $cenozo_db.application_has_cohort
    JOIN $cenozo_db.participant ON application_has_cohort.cohort_id = participant.cohort_id
    LEFT JOIN $cenozo_db.participant_primary_address ON participant.id = participant_primary_address.participant_id
    LEFT JOIN $cenozo_db.address ON participant_primary_address.address_id = address.id
    LEFT JOIN $cenozo_db.region ON address.region_id = region.id
    LEFT JOIN $app_db.region_site ON region.id = region_site.region_id
    LEFT JOIN $cenozo_db.site AS region_site_site
      ON region_site.site_id = region_site_site.id
      AND participant.language_id = region_site.language_id
    LEFT JOIN $cenozo_db.application_has_participant
      ON application_has_cohort.application_id = application_has_participant.application_id
      AND application_has_participant.participant_id = participant.id
    WHERE region_site.site_id <=> region_site_site.id
    AND application_has_cohort.application_id = {$row['application_id']}
    AND application_has_cohort.grouping = "region"
    AND region_site.id = OLD.id;

  END
SQL );

        out( sprintf( 'Creating %s.update_participant_site_for_jurisdiction procedure', $app_db ) );
        $this->query( <<<SQL
CREATE PROCEDURE $app_db.update_participant_site_for_jurisdiction( IN proc_jurisdiction_id INT(10) UNSIGNED )
  BEGIN

    REPLACE INTO $cenozo_db.participant_site( application_id, participant_id, site_id, default_site_id )
    SELECT
      application_has_cohort.application_id,
      participant.id,
      IF(
        ISNULL( application_has_participant.preferred_site_id ),
        jurisdiction.site_id,
        application_has_participant.preferred_site_id
      ) AS site_id,
      jurisdiction.site_id AS default_site_id
    FROM $cenozo_db.application_has_cohort
    JOIN $cenozo_db.participant ON application_has_cohort.cohort_id = participant.cohort_id
    LEFT JOIN $cenozo_db.participant_primary_address ON participant.id = participant_primary_address.participant_id
    LEFT JOIN $cenozo_db.address ON participant_primary_address.address_id = address.id
    LEFT JOIN $app_db.jurisdiction ON address.postcode = jurisdiction.postcode
    LEFT JOIN $cenozo_db.site AS jurisdiction_site ON jurisdiction.site_id = jurisdiction_site.id
    LEFT JOIN $cenozo_db.application_has_participant
      ON application_has_cohort.application_id = application_has_participant.application_id
      AND application_has_participant.participant_id = participant.id
    WHERE jurisdiction.site_id <=> jurisdiction_site.id
    AND application_has_cohort.application_id = {$row['application_id']}
    AND application_has_cohort.grouping = "jurisdiction"
    AND jurisdiction.id = proc_jurisdiction_id;

  END
SQL );

        // Create update_participant_site_for_region_site
        out( sprintf( 'Creating %s.update_participant_site_for_region_site procedure', $app_db ) );
        $this->query( sprintf( 'DROP PROCEDURE IF EXISTS %s.update_participant_site_for_region_site', $app_db ) );

        $this->query( <<<SQL
CREATE PROCEDURE $app_db.update_participant_site_for_region_site( IN proc_region_site_id INT(10) UNSIGNED )
  BEGIN
      REPLACE INTO $cenozo_db.participant_site( application_id, participant_id, site_id, default_site_id )
      SELECT
        application_has_cohort.application_id,
        participant.id,
        IF(
          ISNULL( application_has_participant.preferred_site_id ),
          region_site.site_id,
          application_has_participant.preferred_site_id
        ) AS site_id,
        region_site.site_id AS default_site_id
      FROM $cenozo_db.application_has_cohort
      JOIN $cenozo_db.participant ON application_has_cohort.cohort_id = participant.cohort_id
      LEFT JOIN $cenozo_db.participant_primary_address
        ON participant.id = participant_primary_address.participant_id
      LEFT JOIN $cenozo_db.address ON participant_primary_address.address_id = address.id
      LEFT JOIN $cenozo_db.region ON address.region_id = region.id
      LEFT JOIN $app_db.region_site ON region.id = region_site.region_id
      LEFT JOIN $cenozo_db.site AS region_site_site
        ON region_site.site_id = region_site_site.id
        AND participant.language_id = region_site.language_id
      LEFT JOIN $cenozo_db.application_has_participant
        ON application_has_cohort.application_id = application_has_participant.application_id
        AND application_has_participant.participant_id = participant.id
      WHERE region_site.site_id <=> region_site_site.id
      AND application_has_cohort.application_id = {$row['application_id']}
      AND application_has_cohort.grouping = "region"
      AND region_site.id = proc_region_site_id;
  END
SQL );
      }
      else if( 'mastodon' == $row['application_type_name'] )
      {
        $forms = ['consent', 'extended_hin', 'general_proxy', 'hin', 'proxy', 'dm_consent', 'ip_consent'];
        foreach( $forms as $name )
        {
          $procedure_name = sprintf( 'update_%s_form_total', $name );
          out( sprintf( 'Creating %s.%s procedure', $app_db, $procedure_name ) );

          $sql = sprintf( 'DROP PROCEDURE IF EXISTS %s.%s', $app_db, $procedure_name );
          $this->query( $sql );

          $this->query( <<<SQL
CREATE PROCEDURE $app_db.$procedure_name( IN proc_{$name}_form_id INT(10) UNSIGNED )
  BEGIN

    SELECT validated_{$name}_form_entry_id INTO @validated_id
    FROM $app_db.{$name}_form
    WHERE id = proc_{$name}_form_id;

    IF @validated_id THEN

      REPLACE INTO $app_db.{$name}_form_total
      SET
        {$name}_form_id = proc_{$name}_form_id,
        entry_total = (
          SELECT COUNT(*) FROM $app_db.{$name}_form_entry
          WHERE {$name}_form_id = proc_{$name}_form_id
        ),
        submitted_total = (
          SELECT COUNT(*) FROM $app_db.{$name}_form_entry
          WHERE {$name}_form_id = proc_{$name}_form_id
          AND submitted = true
        ),
        uid = (
          SELECT participant.uid
          FROM $app_db.{$name}_form_entry
          LEFT JOIN $cenozo_db.participant ON {$name}_form_entry.participant_id = participant.id
          WHERE {$name}_form_entry.id = @validated_id
        ),
        cohort = (
          SELECT cohort.name
          FROM $app_db.{$name}_form_entry
          LEFT JOIN $cenozo_db.participant ON {$name}_form_entry.participant_id = participant.id
          LEFT JOIN $cenozo_db.cohort ON participant.cohort_id = cohort.id
          WHERE {$name}_form_entry.id = @validated_id
        );

    ELSE

      REPLACE INTO $app_db.{$name}_form_total
      SET
        {$name}_form_id = proc_{$name}_form_id,
        entry_total = (
          SELECT COUNT(*) FROM $app_db.{$name}_form_entry
          WHERE {$name}_form_id = proc_{$name}_form_id
        ),
        submitted_total = (
          SELECT COUNT(*) FROM $app_db.{$name}_form_entry
          WHERE {$name}_form_id = proc_{$name}_form_id
          AND submitted = true
        ),
        uid = (
          SELECT GROUP_CONCAT( DISTINCT participant.uid ORDER BY participant.uid SEPARATOR ',' )
          FROM $app_db.{$name}_form_entry
          LEFT JOIN $cenozo_db.participant ON {$name}_form_entry.participant_id = participant.id
          WHERE {$name}_form_id = proc_{$name}_form_id
          GROUP BY {$name}_form_id
        ),
        cohort = (
          SELECT GROUP_CONCAT( DISTINCT cohort.name ORDER BY cohort.name SEPARATOR ',' )
          FROM $app_db.{$name}_form_entry
          LEFT JOIN $cenozo_db.participant ON {$name}_form_entry.participant_id = participant.id
          LEFT JOIN $cenozo_db.cohort ON participant.cohort_id = cohort.id
          WHERE {$name}_form_id = proc_{$name}_form_id
          GROUP BY {$name}_form_id
        );

    END IF;

  END
SQL );
        }
      }
    }

    $update_participant_site_for_participant_sql .= "  END";

    out( sprintf( 'Creating %s.update_participant_site_for_participant procedure', $cenozo_db ) );
    $sql = sprintf( 'DROP PROCEDURE IF EXISTS %s.update_participant_site_for_participant', $cenozo_db );
    $this->query( $sql );
    $this->query( $update_participant_site_for_participant_sql );
    out( 'Done' );
  }

  /**
   * Contains all initialization parameters.
   * @var array
   * @access private
   */
  private $settings = [];

  /**
   * The mysqli object used to communicate with the database
   * @var mysqli
   */
  private $db = NULL;
}

$patch = new patch();
$patch->execute();
